version: '2'
services:
    appdroits-app:
        image: appdroits
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://appdroits-postgresql:5432/appdroits
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    appdroits-postgresql:
        extends:
            file: postgresql.yml
            service: appdroits-postgresql
